{
 "title": "CHT新莊機房 smokeping",
 "description": "新莊對外連線狀況",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "packet lost (%)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smokeping_lost_package_num{instance=~\".*\",job=\"smokeping-collected\", alias=~'.*'} / 60 * 100",
     "legendFormat": "{{ alias}}"
    }
   ]
  },
  {
   "title": "Delay top10 (ms)",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "topk(10 , smokeping_rrt{instance=~\".*\",job=\"smokeping-collected\" , alias=~'.*'})",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "Delay list (ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smokeping_rrt{instance=~\".*\",job=\"smokeping-collected\" , alias=~'.*'}",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "Delay list (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smokeping_rrt{instance=~\".*\",job=\"smokeping-collected\" , alias=~'.*'}",
     "legendFormat": "{{ alias }}"
    }
   ]
  }
 ]
}